version: "3.7"
services:
  api_service:
    build: ./user-services/
    restart: always
    ports:
      - 8081:8081
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/e-commerce?allowPublicKeyRetrieval=true
      - spring.datasource.user=e_commerce_user
      - spring.datasource.password=e_commerce_password
    depends_on:
      - mysqldb
    volumes:
      - .m2:/Users/skaruppiah/.m2
  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: e-commerce
      MYSQL_USER: e_commerce_user
      MYSQL_PASSWORD: e_commerce_password
      MYSQL_ROOT_PASSWORD: root
networks:
  springapimysql-net: