version: "3.7"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: e-commerce
      MYSQL_USER: e_commerce_user
      MYSQL_PASSWORD: e_commerce_password
      MYSQL_ROOT_PASSWORD: your_root_password
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: your_root_password
    ports:
      - '8071:80'
    networks:
      - app-network
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.3
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
networks:
  app-network:
    driver: bridge
volumes:
  db_data: