version: "3.7"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: e-commerce
      MYSQL_USER: e_commerce_user
      MYSQL_PASSWORD: e_commerce_password
      MYSQL_ROOT_PASSWORD: your_root_password
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: your_root_password
    ports:
      - '8071:80'
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  db_data: