version: "3.7"
services:
  api_service:
    build: ./user-service/
    restart: always
    ports:
      - 8081:8081
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/e-commerce?allowPublicKeyRetrieval=true
      - spring.datasource.user=e_commerce_user
      - spring.datasource.password=e_commerce_password
    depends_on:
      - db
    volumes:
      - .m2:/Users/skaruppiah/.m2
    networks:
      - app-network
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: e-commerce
      MYSQL_USER: e_commerce_user
      MYSQL_PASSWORD: e_commerce_password
      MYSQL_ROOT_PASSWORD: your_root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: your_root_password
    ports:
      - '8071:80'
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  db_data: