spring:
  application:
    name: user-service
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    database-platform: org.hibernate.dialect.MySQLDialect
    url: jdbc:mysql://localhost:3306/e-commerce?allowPublicKeyRetrieval=true
    username: e_commerce_user
    password: e_commerce_password

server:
  servlet:
    context-path: /api/v1
  port: 8081

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
management:
  endpoint:
    health:
      probes:
        enabled: true
  tracing:
    baggage:
      remote-fields: email, User-ClientIp, User-ClientPort, User-SessionId, App-Channel, Channel-Type, Language-Prefix, App-Version, Os-Version
      correlation:
        fields: email, User-ClientIp, User-ClientPort, User-SessionId, App-Channel, Channel-Type, Language-Prefix, App-Version, Os-Version